### ISSUE TITLE
Waiting for Debugger

### ISSUE THREAD

**Issue by SaguruHakuba** [adelphes/android-dev-ext#60] opened 2019-06-11 17:14 UTC
Hi! I used gradle to build the android project and tried to run the google map activity sample from android studio on vscode, with the automatically generated configuration. I ran into the problem that on my apk emulator device, it is telling me that it is "Waiting for the debugger". I could not find any similar problem shown up using the vscode extension. 
![image](https://user-images.githubusercontent.com/22808988/59292310-d1fd0780-8c4a-11e9-929b-d2a5ff18ee92.png)
Thus, I am here to see if anyone have run into this before.

**Comment by SaguruHakuba** [comment] 2019-06-11 17:15
Here is the launch configuration auto-generated.
![image](https://user-images.githubusercontent.com/22808988/59292420-083a8700-8c4b-11e9-9be1-ad1b3f2bf4a7.png)

**Comment by SaguruHakuba** [comment] 2019-06-11 17:16
And here is what debugger console says
![image](https://user-images.githubusercontent.com/22808988/59292448-1a1c2a00-8c4b-11e9-8214-07496093f93d.png)

**Comment by SaguruHakuba** [comment] 2019-06-11 17:18
And here is what debugger console says
![image](https://user-images.githubusercontent.com/22808988/59292565-55b6f400-8c4b-11e9-9236-b1eff8d246fb.png)

**Comment by adelphes** [comment] 2019-06-27 11:03
Thanks for the information. This sometimes happens when an app uses an external library or API that isn't supported by the emulator. The app refuses to start (because of the missing methods), but the debugger is not notified.

A couple of things to try:
- is there any exception, stack-trace or errors in logcat that shows why the app isn't starting?
- can you try enabling trace in your configuration and see if there's any more info in the output:

```
{
  ...
  "adbPort": 5037,
  "trace": true
}
```

**Comment by MrMuMu** [comment] 2019-10-02 15:19
I have the same issue, running the built-in hello world example on GM 5 Plus.
![image](https://user-images.githubusercontent.com/11612804/66057208-f9047f80-e540-11e9-8fb3-43a4bc2b7409.png)

it hangs like this, and the phone screen is like author's

**Comment by adelphes** [comment] 2019-10-02 15:42
@MrMuMu when it hangs, can you run `adb logcat` in a terminal and see if there are any crashes or errors being reported.

**Comment by MrMuMu** [comment] 2019-10-02 15:55
There are a lot exceptions and they keep coming:), here is a screenshot:
![image](https://user-images.githubusercontent.com/11612804/66060244-fbb5a380-e545-11e9-9f46-0516d3fafeb9.png)

**Comment by adelphes** [comment] 2019-10-02 16:02
Part of the problem may be the wrong date and time. Lots of services will not work if your device time is too far ahead or behind.
Your logcat is showing the current date/time to be November 24th around midnight. Could you correct the time on the device and see if that makes a difference (or log any new errors).

**Comment by MrMuMu** [comment] 2019-10-03 06:07
I have changed the time, here is the snap of the new logs:
![image](https://user-images.githubusercontent.com/11612804/66103050-20009700-e5bd-11e9-84de-bdc2a7544327.png)

By the way the application works if I use android studio.

**Comment by adelphes** [comment] 2019-10-03 09:20
OK - thanks for trying again. There is a line in the log that's showing an issue:

```
10-03 21:03:29.858 E/art ( 1177): Failed sending reply to debugger: Broken pipe
```
This probably means the connection between the device and the debugger failed. Normally this is caused by a debugger crash on the device or a faulty cable (or bad network connection if debugging over WiFi). But if it works with AS, I'm not sure what's going on.

If you're able to upload the full logcat (not just the errors), that would be extremely useful. If not, I will try and reproduce it another way.
Thanks again for your help with this.

**Comment by MrMuMu** [comment] 2019-10-03 11:16
I can share the whole file but I do not know how, I am new to android world sorry :) Is there any way to export or where is file location?

It works over cable and it works on android studio as is right now.

**Comment by rvbcrs** [comment] 2020-01-09 07:44
Hi, any news on this? I'm running into the same issue. The debugger fails to attach. Sometimes it connects the first time, sometimes I have to try 2 or 3 times before it connects and I'm able to debug.

The debug console stays at this line:
`Launching /.MainActivity on device ce091820d6cf61721a8e [API:28]`

Logcat says:
`2020-01-09 08:43:00.237 14296-14296/? I/ringen.beta_ac: Late-enabling -Xcheck:jni
2020-01-09 08:43:00.329 14296-14296/ W/ActivityThread: Application is waiting for the debugger on port 8100...
2020-01-09 08:43:00.329 14296-14296/ I/System.out: Sending WAIT chunk`

**Comment by MrMuMu** [comment] 2020-01-09 07:48
Is android studio open?

**Comment by rvbcrs** [comment] 2020-01-09 08:13
> Is android studio open?

It was, but now I closed it, still same problem

**Comment by MrMuMu** [comment] 2020-01-09 08:21
Can you try like this:

- Delete application
- Restart phone
- Debug with vscode provided that android studio is not open

**Comment by rvbcrs** [comment] 2020-01-09 14:45
> Can you try like this:
> 
> * Delete application
> * Restart phone
> * Debug with vscode provided that android studio is not open

I must say it works WAY better now, since I closed Android studio!! It now works great every time!

**Comment by adelphes** [comment] 2020-04-24 18:44
Closing - the issue is likely due to conflicts with Android Studio.

**Closed by adelphes** 2020-04-24 18:44 UTC
